# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb.proto',
  package='com.iohao.message',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08pb.proto\x12\x11\x63om.iohao.message\"\x93\x01\n\x0f\x45xternalMessage\x12\x0f\n\x07\x63mdCode\x18\x01 \x01(\x05\x12\x16\n\x0eprotocolSwitch\x18\x02 \x01(\x05\x12\x10\n\x08\x63mdMerge\x18\x03 \x01(\x05\x12\x16\n\x0eresponseStatus\x18\x04 \x01(\x11\x12\x10\n\x08validMsg\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12\r\n\x05msgId\x18\x07 \x01(\x05\x62\x06proto3'
)




_EXTERNALMESSAGE = _descriptor.Descriptor(
  name='ExternalMessage',
  full_name='com.iohao.message.ExternalMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdCode', full_name='com.iohao.message.ExternalMessage.cmdCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocolSwitch', full_name='com.iohao.message.ExternalMessage.protocolSwitch', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmdMerge', full_name='com.iohao.message.ExternalMessage.cmdMerge', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseStatus', full_name='com.iohao.message.ExternalMessage.responseStatus', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='validMsg', full_name='com.iohao.message.ExternalMessage.validMsg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='com.iohao.message.ExternalMessage.data', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msgId', full_name='com.iohao.message.ExternalMessage.msgId', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=179,
)

DESCRIPTOR.message_types_by_name['ExternalMessage'] = _EXTERNALMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExternalMessage = _reflection.GeneratedProtocolMessageType('ExternalMessage', (_message.Message,), {
  'DESCRIPTOR' : _EXTERNALMESSAGE,
  '__module__' : 'pb_pb2'
  # @@protoc_insertion_point(class_scope:com.iohao.message.ExternalMessage)
  })
_sym_db.RegisterMessage(ExternalMessage)


# @@protoc_insertion_point(module_scope)
